### ISSUE TITLE
Just link to recipes (vignettes) from R package docs

### ISSUE THREAD

**Issue by vincerubinetti** [blekhmanlab/compendium_website#16]
The contents of the recipes are going to be built into the R package, on the docs site for it:

https://pkgdown.r-lib.org/

Instead of duplicating this info on the website, let's have the package just be the one source of truth and just link to it. We can still include the titles of the recipes on the website so people can get a quick idea.

**Comment by seandavi** [comment]
Docs currently hosted here: https://seandavi.github.io/MicroBioMap/
