### ISSUE TITLE
Store local copy of Natural Earth data

### ISSUE THREAD

**Issue by rabdill** [blekhmanlab/compendium_website#19]
The first step in the `processNaturalEarth` function in the compilation script currently fetches the most recent "ne_110m_admin_0_countries" Natural Earth data. This is probably as reliable a source as any, but it would still fail from changes to file names or organization. It looks like the file is small enough that it would be practical to store a copy of it and update later if there's a new release—would that be preferable? It couldn't hurt to stay updated, but it doesn't seem urgent enough that we need to pull straight from master every time. It looks like [their license](https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md) wouldn't preclude this.

**Comment by seandavi** [comment]
It seems a good idea. Perhaps drop that file in the Zenodo release?
