### ISSUE TITLE
Bar chart dimensions shouldn't change with different filters

### ISSUE THREAD

**Issue by rabdill** [blekhmanlab/compendium_website#20]
The "By Phylum" prevalence chart appears to resize itself slightly when the width of the x-axis changes. This isn't an issue when switching between the unfiltered chart and several of the regional ones, but it's more obvious when choosing:
* Europe and Northern America
* Latin America and the Caribbean
* Eastern and South-Eastern Asia
* Australia/New Zealand

It makes sense that the scale of the x-axis would change, but it looks like small changes to the width of the chart also impact the height of the chart, which is more noticeable. Not a huge deal, but if there's a straightforward way to stay within a static box, that could help.

![resizing](https://github.com/blekhmanlab/compendium_website/assets/6011419/8b032ae1-d218-4d0f-850d-385d74497ee4)

**Comment by vincerubinetti** [comment]
The way I did this was to make sure everything was always in view. I've changed it to static locally and will open a PR soon. It looks nicer, but with the tradeoff that one of the longer x-axis labels may get cutoff on smaller screens.
