### ISSUE TITLE
Add basic search functionality

### ISSUE THREAD

**Issue by vincerubinetti** [blekhmanlab/compendium_website#4]
I think it would be useful for people to be able to quickly check (without having to download the whole dataset) if there is a particular class/phylum/country/region, and how many samples it has. Just a basic search box that returns a list of results, like:

`Search: Sah`

|Match|Type|Samples|
|-|-|-|
|Sub-saharan Africa|Region|12,345|
|saharious firmicutes|Class|678|

etc.

**Comment by rabdill** [comment]
This is a great idea, and the "type" column finally made it click for me how it would work. The only addition I suggest is to include project IDs as one of the searchable fields—the ones that start `PRJ`, usually something like `PRJNA111111`. That would be helpful if a person is looking for processed data from a single project and is curious if we've gotten to it.
