### ISSUE TITLE
Dataset high level metadata

### ISSUE THREAD

**Issue by vincerubinetti** [blekhmanlab/compendium_website#9]
It's usually nice, for advertising purposes, to "show off" how many X we have in the data. Here are some thing we might want to show off right at the top of the website, either in paragraph "hero" form, or in [tile form](https://github.com/blekhmanlab/compendium_website/assets/8326331/0a500631-e3fc-4ea3-a71f-f1c1934f3fb8):

- number of samples
- number of projects?
- number of classes/phyla?
- countries/regions?
- size of the dataset download?

**Comment by rabdill** [comment]
This is definitely one that we can build into the dataset release process—it's certainly possible to infer most of the relevant stats from the dataset you have, but it's probably much easier for us to do it. I personally like the tile format, but not enough to argue in favor of it if anyone else has a preference. Either way, we could generate a JSON file that looked something like this:

```json
[
    {
        "description": "samples",
        "value": 168646,
        "icon": "petri.svg"
    },
    {
        "description": "countries",
        "value": 168,
        "icon": "globe.svg"
    }
]
```
We'd still need to track down the actual icons, but would this give you everything you need?

**Comment by vincerubinetti** [comment]
I don't think you need to include the icons, I can handle that, and that's only really needed for the website. People looking at the json directly (if there is anyone doing that) wouldn't care about the icon.

As such, I think you can do a simpler structure. This is akin to how I've seen other APIs do a "metadata" endpoint before:

```js
{
  samples: 123456,
  countries: 123,
  phyla: 123,
}
```

**Comment by rabdill** [comment]
Oh great! That would be much easier, I just figured you wouldn't want to maintain a whole separate list of icons. We can definitely do it this way.

**Comment by vincerubinetti** [comment]
Icons aren't a big deal. Font Awesome has a ton, and I've designed tons of custom icons before too. Since this metadata is likely to be small and stable, it's no problem to just hard code the icon to the field name in the website.
